name: courbes
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10
  - numpy~=1.26.4
  - pandas~=2.2.1
  - mdtraj~=1.9.9
  - importlib_metadata~=7.1.0
  - scipy~=1.11.4
  - prolif~=2.0.3
  - mdanalysis~=2.7.0
  - setuptools~=68.2.2
  - ipython~=8.22.2
  - tqdm~=4.66.4

  - pip
  - tqdm
  - matplotlib
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark

  - pip:
      - -e .  # install git checkout of courbes in editable mode
